### ISSUE TITLE
Video de demo mp4

### ISSUE THREAD

**Issue by adriens** [adriens/colisnc-discord#13]
Dropper sur ce ticket une démo au format mp4 om l'on interroge le bot avec la commande `slash` et où le bot répond.

Livraison pour demain svp.

**Comment by ini-ruku** [comment]
[Demo OPT- Bot.zip](https://github.com/adriens/colisnc-discord/files/6418857/Demo.OPT-.Bot.zip)

**Comment by adriens** [comment]
https://user-images.githubusercontent.com/5235127/116962759-a4b01b80-acf2-11eb-9b29-054ba3b4d215.mp4

**Comment by adriens** [comment]
Merci @lucEnee 👍

**Comment by adriens** [comment]
https://youtu.be/Yp4eGGpgzNA
