### ISSUE TITLE
Vidéos DEMO

### ISSUE THREAD

**Issue by OceanneTly** [adriens/colisnc-discord#14]
Capture des vidéos de tests.

**Comment by adriens** [comment]
J'attends toujours les video du scénario complet surmobile et PC, **sur ce ticket**.

**Comment by adriens** [comment]
J'ai demandé l'accès à plusieurs reprises mais je n'ai toujours pas accès au driver google
![image](https://user-images.githubusercontent.com/5235127/123910097-b269e080-d9c5-11eb-8f07-760f629ab199.png)

**Comment by ini-ruku** [comment]
https://drive.google.com/file/d/1HmuMZpXFqExY-aEy569l4EOqxZUTjGIB/view?usp=sharing

https://drive.google.com/file/d/18IgIYLd_lIA1QZG-YqPwwLvApLXJr5xw/view?usp=sharing

**Comment by adriens** [comment]
Top, merci @lucEnee  👍

**Comment by adriens** [comment]
@lucEnee pour la version laptop, screencast stp au lieu de video prise au téléphone : c'est super lourd et on voit pas bien. L'utilitaire de jeu windows 10 fait ça super propre et sinon Snagit 🙏 
Une fois cela fait, je pourrai fermer le ticket

**Comment by ini-ruku** [comment]
Ok j'essaie de te fournir ça

**Comment by adriens** [comment]
@lucEnee , je peux compter sur les videos ce we ❔

**Comment by adriens** [comment]
Video sur mobile droppée hier par @lucEnee : 

https://user-images.githubusercontent.com/5235127/124322790-d1d25a80-dbcb-11eb-8076-c7e343399f79.MP4

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/124366932-10851500-dc9f-11eb-903c-028b45660208.png)

**Comment by ini-ruku** [comment]
https://drive.google.com/file/d/1ZVmt3KlLO2WThjZFiZmI-gOE8qBB0Ce3/view?usp=sharing

**Comment by adriens** [comment]
https://user-images.githubusercontent.com/5235127/124373618-83ae7b80-dcdf-11eb-9860-16a15ecc9589.mp4

**Comment by adriens** [comment]
Yes, c'est good 👏

**Comment by adriens** [comment]
https://youtube.com/playlist?list=PLVaySOddZPMe59cMtDSFDhNNV8s30PREl
