### ISSUE TITLE
Logo OPT pour le serveur

### ISSUE THREAD

**Issue by adriens** [adriens/colisnc-discord#9]
# Contexte

Actuellement il n'y pas de Logo, mettre un logo rendrait le serveur plus facile à identifier

![image](https://user-images.githubusercontent.com/5235127/111577652-ca4a9980-8806-11eb-9d6f-c05c18e0ea96.png)

Genre logo ci-dessous si la définitoin est ok 👍 

![image](https://user-images.githubusercontent.com/5235127/111577709-ee0ddf80-8806-11eb-81d0-5a6df00fd82b.png)

**Comment by ini-ruku** [comment]
The image of the Discord server has been modified by the OPT logo

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/116939255-c809a500-acb7-11eb-8776-488292b63447.png)
